/*
  # Activities short share URL + share message (COD-ACTIVITIES-SHORT-SHARE-URL-088)

  Purpose:
  - Provide a permanent, short website URL for published activities that survives
    slug changes.
  - Allow admins to refresh/regenerate the short URL when needed.
  - Store an AI-generated short share message for reuse on the public activity page.
*/

ALTER TABLE public.activities
  ADD COLUMN IF NOT EXISTS short_url_code text,
  ADD COLUMN IF NOT EXISTS share_message text;

COMMENT ON COLUMN public.activities.short_url_code IS
  'Permanent short redirect code for published activity sharing (e.g., /a/abc123x).';

COMMENT ON COLUMN public.activities.share_message IS
  'Short public share message for the activity, generated by AI or edited server-side.';

CREATE OR REPLACE FUNCTION public.gen_activity_short_url_code_candidate()
RETURNS text
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
  v_chars constant text := '23456789abcdefghjkmnpqrstuvwxyz';
  v_code text := '';
  v_i integer;
BEGIN
  FOR v_i IN 1..7 LOOP
    v_code := v_code || substr(v_chars, 1 + floor(random() * length(v_chars))::int, 1);
  END LOOP;
  RETURN v_code;
END;
$$;

CREATE OR REPLACE FUNCTION public.generate_unique_activity_short_url_code(
  p_exclude_activity_id uuid DEFAULT NULL
)
RETURNS text
LANGUAGE plpgsql
VOLATILE
AS $$
DECLARE
  v_code text;
  v_attempt integer := 0;
BEGIN
  LOOP
    v_attempt := v_attempt + 1;
    v_code := public.gen_activity_short_url_code_candidate();

    EXIT WHEN NOT EXISTS (
      SELECT 1
      FROM public.activities a
      WHERE lower(a.short_url_code) = lower(v_code)
        AND (p_exclude_activity_id IS NULL OR a.id <> p_exclude_activity_id)
    );

    IF v_attempt >= 50 THEN
      RAISE EXCEPTION 'Could not generate unique activity short URL code after % attempts', v_attempt;
    END IF;
  END LOOP;

  RETURN lower(v_code);
END;
$$;

CREATE OR REPLACE FUNCTION public.activities_before_insert_set_short_url_code()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.short_url_code IS NULL OR btrim(NEW.short_url_code) = '' THEN
    NEW.short_url_code := public.generate_unique_activity_short_url_code(NEW.id);
  ELSE
    NEW.short_url_code := lower(btrim(NEW.short_url_code));
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS activities_before_insert_set_short_url_code ON public.activities;
CREATE TRIGGER activities_before_insert_set_short_url_code
BEFORE INSERT ON public.activities
FOR EACH ROW
EXECUTE FUNCTION public.activities_before_insert_set_short_url_code();

UPDATE public.activities a
SET short_url_code = public.generate_unique_activity_short_url_code(a.id)
WHERE a.short_url_code IS NULL OR btrim(a.short_url_code) = '';

UPDATE public.activities
SET short_url_code = lower(btrim(short_url_code))
WHERE short_url_code IS NOT NULL
  AND short_url_code <> lower(btrim(short_url_code));

CREATE UNIQUE INDEX IF NOT EXISTS activities_short_url_code_uidx
  ON public.activities (lower(short_url_code));

CREATE OR REPLACE FUNCTION public.resolve_activity_short_url(
  p_short_code text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_code text := lower(btrim(COALESCE(p_short_code, '')));
  v_slug text;
BEGIN
  IF v_code = '' THEN
    RETURN jsonb_build_object(
      'success', false,
      'error_code', 'invalid_code',
      'error', 'Short URL code is required'
    );
  END IF;

  SELECT a.slug
  INTO v_slug
  FROM public.activities a
  WHERE lower(a.short_url_code) = v_code
    AND a.status = 'published'
  LIMIT 1;

  IF v_slug IS NULL THEN
    RETURN jsonb_build_object(
      'success', false,
      'error_code', 'not_found',
      'error', 'Short URL not found'
    );
  END IF;

  RETURN jsonb_build_object(
    'success', true,
    'data', jsonb_build_object(
      'slug', v_slug,
      'short_code', v_code,
      'target_path', '/events/' || v_slug
    )
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.resolve_activity_short_url(text) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.ensure_activity_short_url_with_session(
  p_session_token text,
  p_activity_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_actor_id uuid;
  v_activity public.activities%ROWTYPE;
  v_short_code text;
BEGIN
  v_actor_id := public.resolve_custom_session_user_id(p_session_token);
  IF v_actor_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error_code', 'invalid_session', 'error', 'Invalid session');
  END IF;

  IF NOT public.has_permission(v_actor_id, 'activities.view') THEN
    RETURN jsonb_build_object('success', false, 'error_code', 'permission_denied', 'error', 'Not authorized');
  END IF;

  SELECT * INTO v_activity FROM public.activities WHERE id = p_activity_id LIMIT 1;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error_code', 'not_found', 'error', 'Activity not found');
  END IF;

  v_short_code := lower(btrim(COALESCE(v_activity.short_url_code, '')));
  IF v_short_code = '' THEN
    v_short_code := public.generate_unique_activity_short_url_code(v_activity.id);
    UPDATE public.activities
    SET short_url_code = v_short_code,
        updated_at = now()
    WHERE id = v_activity.id;
  END IF;

  RETURN jsonb_build_object(
    'success', true,
    'data', jsonb_build_object(
      'activity_id', v_activity.id,
      'short_code', v_short_code
    )
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.ensure_activity_short_url_with_session(text, uuid) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.refresh_activity_short_url_with_session(
  p_session_token text,
  p_activity_id uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_actor_id uuid;
  v_activity public.activities%ROWTYPE;
  v_short_code text;
BEGIN
  v_actor_id := public.resolve_custom_session_user_id(p_session_token);
  IF v_actor_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error_code', 'invalid_session', 'error', 'Invalid session');
  END IF;

  SELECT * INTO v_activity FROM public.activities WHERE id = p_activity_id LIMIT 1;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error_code', 'not_found', 'error', 'Activity not found');
  END IF;

  IF NOT public.has_permission(v_actor_id, 'activities.edit_any') THEN
    IF NOT public.has_permission(v_actor_id, 'activities.edit_own') THEN
      RETURN jsonb_build_object('success', false, 'error_code', 'permission_denied', 'error', 'Not authorized');
    END IF;
    IF v_activity.created_by IS DISTINCT FROM v_actor_id THEN
      RETURN jsonb_build_object('success', false, 'error_code', 'permission_denied', 'error', 'Not authorized');
    END IF;
  END IF;

  v_short_code := public.generate_unique_activity_short_url_code(v_activity.id);
  UPDATE public.activities
  SET short_url_code = v_short_code,
      updated_at = now()
  WHERE id = v_activity.id;

  RETURN jsonb_build_object(
    'success', true,
    'data', jsonb_build_object(
      'activity_id', v_activity.id,
      'short_code', v_short_code
    )
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.refresh_activity_short_url_with_session(text, uuid) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.save_activity_share_message_with_session(
  p_session_token text,
  p_activity_id uuid,
  p_share_message text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_actor_id uuid;
  v_activity public.activities%ROWTYPE;
  v_message text := NULLIF(btrim(COALESCE(p_share_message, '')), '');
BEGIN
  v_actor_id := public.resolve_custom_session_user_id(p_session_token);
  IF v_actor_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error_code', 'invalid_session', 'error', 'Invalid session');
  END IF;

  SELECT * INTO v_activity FROM public.activities WHERE id = p_activity_id LIMIT 1;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error_code', 'not_found', 'error', 'Activity not found');
  END IF;

  IF NOT public.has_permission(v_actor_id, 'activities.edit_any') THEN
    IF NOT public.has_permission(v_actor_id, 'activities.edit_own') THEN
      RETURN jsonb_build_object('success', false, 'error_code', 'permission_denied', 'error', 'Not authorized');
    END IF;
    IF v_activity.created_by IS DISTINCT FROM v_actor_id THEN
      RETURN jsonb_build_object('success', false, 'error_code', 'permission_denied', 'error', 'Not authorized');
    END IF;
  END IF;

  IF v_message IS NOT NULL THEN
    v_message := left(v_message, 700);
  END IF;

  UPDATE public.activities
  SET share_message = v_message,
      updated_at = now()
  WHERE id = v_activity.id;

  RETURN jsonb_build_object(
    'success', true,
    'data', jsonb_build_object(
      'activity_id', v_activity.id,
      'share_message', v_message
    )
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.save_activity_share_message_with_session(text, uuid, text) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.get_activity_by_slug(p_slug text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_activity  public.activities%ROWTYPE;
  v_media     jsonb;
  v_first_media_url text;
BEGIN
  SELECT * INTO v_activity
  FROM public.activities
  WHERE slug = p_slug AND status = 'published';

  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Activity not found');
  END IF;

  SELECT m.storage_url INTO v_first_media_url
  FROM public.activity_media m
  WHERE m.activity_id = v_activity.id
  ORDER BY m.display_order ASC, m.created_at ASC
  LIMIT 1;

  SELECT jsonb_agg(
    jsonb_build_object(
      'id',            m.id,
      'storage_url',   m.storage_url,
      'display_order', m.display_order
    )
    ORDER BY m.display_order ASC
  )
  INTO v_media
  FROM public.activity_media m
  WHERE m.activity_id = v_activity.id;

  RETURN jsonb_build_object(
    'success', true,
    'data', jsonb_build_object(
      'id',              v_activity.id,
      'slug',            v_activity.slug,
      'short_url_code',  v_activity.short_url_code,
      'share_message',   v_activity.share_message,
      'title',           v_activity.title,
      'excerpt',         v_activity.excerpt,
      'description',     v_activity.description,
      'activity_date',   v_activity.activity_date,
      'start_at',        v_activity.start_at,
      'end_at',          v_activity.end_at,
      'location',        v_activity.location,
      'cover_image_url', public.activity_cover_seed_url(COALESCE(NULLIF(v_activity.cover_image_url, ''), v_first_media_url)),
      'is_featured',     v_activity.is_featured,
      'youtube_urls',    v_activity.youtube_urls,
      'published_at',    v_activity.published_at,
      'media',           COALESCE(v_media, '[]'::jsonb)
    )
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_activity_by_slug(text) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.get_activity_by_id_with_session(
  p_session_token text,
  p_activity_id   uuid
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_actor_id uuid;
  v_activity public.activities%ROWTYPE;
  v_source_event public.events%ROWTYPE;
  v_media    jsonb;
BEGIN
  v_actor_id := public.resolve_custom_session_user_id(p_session_token);
  IF v_actor_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'Invalid session');
  END IF;

  IF NOT public.has_permission(v_actor_id, 'activities.view') THEN
    RETURN jsonb_build_object('success', false, 'error', 'Not authorized');
  END IF;

  SELECT * INTO v_activity FROM public.activities WHERE id = p_activity_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Activity not found');
  END IF;

  IF NOT public.has_permission(v_actor_id, 'activities.edit_any') THEN
    IF v_activity.created_by <> v_actor_id THEN
      RETURN jsonb_build_object('success', false, 'error', 'Not authorized to view this activity');
    END IF;
  END IF;

  IF v_activity.source_event_id IS NOT NULL THEN
    SELECT * INTO v_source_event FROM public.events WHERE id = v_activity.source_event_id;
  END IF;

  SELECT jsonb_agg(
    jsonb_build_object(
      'id',                  m.id,
      'storage_url',         m.storage_url,
      'storage_provider',    m.storage_provider,
      'original_object_key', m.original_object_key,
      'original_filename',   m.original_filename,
      'mime_type',           m.mime_type,
      'file_size_bytes',     m.file_size_bytes,
      'width',               m.width,
      'height',              m.height,
      'display_order',       m.display_order,
      'uploaded_by',         m.uploaded_by,
      'created_at',          m.created_at
    )
    ORDER BY m.display_order ASC
  )
  INTO v_media
  FROM public.activity_media m
  WHERE m.activity_id = v_activity.id;

  RETURN jsonb_build_object(
    'success', true,
    'data', jsonb_build_object(
      'id',                        v_activity.id,
      'slug',                      v_activity.slug,
      'short_url_code',            v_activity.short_url_code,
      'share_message',             v_activity.share_message,
      'title',                     v_activity.title,
      'excerpt',                   v_activity.excerpt,
      'description',               v_activity.description,
      'activity_date',             v_activity.activity_date,
      'start_at',                  v_activity.start_at,
      'end_at',                    v_activity.end_at,
      'location',                  v_activity.location,
      'status',                    v_activity.status,
      'is_featured',               v_activity.is_featured,
      'cover_image_url',           v_activity.cover_image_url,
      'cover_storage_provider',    v_activity.cover_storage_provider,
      'cover_original_object_key', v_activity.cover_original_object_key,
      'cover_original_filename',   v_activity.cover_original_filename,
      'cover_original_mime_type',  v_activity.cover_original_mime_type,
      'cover_original_bytes',      v_activity.cover_original_bytes,
      'cover_original_width',      v_activity.cover_original_width,
      'cover_original_height',     v_activity.cover_original_height,
      'youtube_urls',              v_activity.youtube_urls,
      'source_event_id',           v_activity.source_event_id,
      'source_event',              CASE
                                     WHEN v_source_event.id IS NULL THEN NULL
                                     ELSE jsonb_build_object(
                                       'id', v_source_event.id,
                                       'slug', v_source_event.slug,
                                       'title', v_source_event.title,
                                       'status', v_source_event.status,
                                       'start_at', v_source_event.start_at,
                                       'end_at', v_source_event.end_at
                                     )
                                   END,
      'created_by',                v_activity.created_by,
      'published_at',              v_activity.published_at,
      'created_at',                v_activity.created_at,
      'updated_at',                v_activity.updated_at,
      'media',                     COALESCE(v_media, '[]'::jsonb)
    )
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_activity_by_id_with_session(text, uuid) TO authenticated, anon;

NOTIFY pgrst, 'reload schema';
